
//WARNING: This Font is usable only with MikroE GLCD Lib.
//         X-GLCD Lib does not handle this font.

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroeElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : icon8x8
//GLCD FontSize : 8 x 8

const uint8_t icon[] =
{
        0x08, //font width
        0x08, //font height
        0xFE, 0xA2, 0xE2, 0xA2, 0xE2, 0xA3, 0xFE, 0x00,  // Code for char  , load icon
        0x00, 0x3C, 0x3F, 0xFC, 0xFC, 0xBF, 0xBC, 0x00,  // Code for char !, charger icon
        0x68, 0x8C, 0xBE, 0xBF, 0xBE, 0x8C, 0x68, 0x00,  // Code for char ", boost icon
};

